seed: 42
data:
  train_data_path: "/content/IOW_dataset"
  test_size: 0.2
  batch_size: 32
  min_samples: 100
model:
  pretrained_weights: "/content/Ptethesis_Project/best_state (1).pth"
  head_dim: [256,128]
  dropout: 0.5
  num_classes: 43
training:
  num_epochs: 10
  save_path: ""
  lr_head: 1e-3
  lr_base: 1e-4